import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { AiFillLinkedin, AiFillGithub, AiFillGitlab } from 'react-icons/ai';
import {
  BsFillEnvelopeFill,
  BsFillMoonStarsFill,
  BsFillSunFill,
  BsList,
  BsX,
} from 'react-icons/bs';
import { useEffect, useState } from 'react';
import { useWindowSize } from 'react-use/';
import myself from '../public/myself.jpg';
import logo from '../public/da-logo.png';
import study from '../public/bg-study.jpg';
import work from '../public/bg-work.jpg';
import wxp from '../public/bg-wxp.jpg';
import senai from '../public/senai-logo.jpeg';
import telekom from '../public/telekom-logo.jpeg';
import furb from '../public/furb-logo.jpeg';
import vail from '../public/vail-logo.jpeg';
import veralogica from '../public/veralogica-logo.jpeg';
import humber from '../public/humber-logo.jpeg';
import YearInWords from '../utils/yearInWords';
import HandleDownload from '../utils/handleDownload';
import ReactFlagsSelect from 'react-flags-select';
import ScrollLink from '../utils/scroll';

export default function Home(props) {
  const [darkMode, setDarkMode] = useState(true);
  const [isMenuOpened, setMenuOpen] = useState(true);
  const [isLgScreen, setIsLgScreen] = useState(false);
  const [mainSection, setMainSection] = useState(null);
  const { width } = useWindowSize();
  useEffect(() => setDarkMode(true), []);
  useEffect(() => setMenuOpen(false), []);
  useEffect(() => {
    setIsLgScreen(width >= 1024);
    setMenuOpen(false);
  }, [width]);
  useEffect(() => {
    setMainSection(document.getElementsByClassName('main-section')[0]);
  }, []);
  const themeIcon = darkMode ? <BsFillSunFill /> : <BsFillMoonStarsFill />;
  const menuIcon = isMenuOpened ? <BsX size={24} /> : <BsList size={24} />;
  const translation = props.translation[props.locale];

  const handleChangeLanguage = (countryCode) => {
    const locale = Object.keys(props.countryCodes).find(
      (key) => props.countryCodes[key] === countryCode
    );
    props.push('/', undefined, { locale });
  };

  const handleHover = () => {
    if (mainSection) {
      mainSection.classList.add('landing-section');
    }
  };

  const handleLeave = () => {
    if (mainSection) {
      mainSection.classList.remove('landing-section');
    }
  };

  return (
    <div className={`flex flex-col min-h-screen ${darkMode ? 'dark' : ''}`}>
      <Head>
        <title>Diego Arndt Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className='py-10 px-20 flex justify-between sticky top-0 z-50 bg-gray-200 dark:bg-black dark:text-white'>
        <div className='lg:hidden flex items-center'>
          <button onClick={() => setMenuOpen(!isMenuOpened)}>{menuIcon}</button>
        </div>

        <div className={`da-logo ${isLgScreen ? 'lg:contents' : 'hidden'}`}>
          <ScrollLink to='landing'>
            <Image
              src={logo}
              alt='profile-picture'
              layout='fill'
              objectFit='cover'
              className='h-12 w-12'
            />
          </ScrollLink>

          <ul className='flex justify-center items-center'>
            <li className='mx-4 text-lg text-gray-500 hover:text-gray-300 cursor-pointer'>
              <ScrollLink to='about'>About</ScrollLink>
            </li>
            <li className='mx-4 text-lg text-gray-500 hover:text-gray-300 cursor-pointer'>
              <ScrollLink to='skills'>Skills</ScrollLink>
            </li>
            <li className='mx-4 text-lg text-gray-500 hover:text-gray-300 cursor-pointer'>
              <ScrollLink to='career'>Career</ScrollLink>
            </li>
            <li className='mx-4 text-lg text-gray-500 hover:text-gray-300 cursor-pointer'>
              <ScrollLink to='contact'>Say hello</ScrollLink>
            </li>
          </ul>
        </div>

        <ul className='flex items-center'>
          <li>
            <ReactFlagsSelect
              countries={Object.values(props.countryCodes)}
              customLabels={props.customLabels}
              selected={props.countryCodes[props.locale]}
              onSelect={handleChangeLanguage}
              showSelectedLabel={false}
              showSecondarySelectedLabel={false}
              fullWidth={false}
              placeholder='Language'
              className='react-flags-select px-4 py-2'
            />
          </li>
          <li>
            <div className='transform hover:scale-110 px-4 py-2'>
              <span
                onClick={() => setDarkMode(!darkMode)}
                className='cursor-pointer text-2xl hover:text-blue-600 dark:hover:text-yellow-400'
              >
                {themeIcon}
              </span>
            </div>
          </li>
          <li>
            <div className='pl-4 py-2'>
              <a
                className='cursor-pointer bg-gradient-to-r from-red-600 to-orange-600 hover:from-orange-600 hover:to-red-600 text-white px-4 py-2 border-none rounded-md'
                onClick={HandleDownload}
                tooltip='Download resume'
              >
                {translation.resume}
              </a>
            </div>
          </li>
        </ul>
      </nav>

      <main
        className={`flex-grow bg-gray-200 dark:bg-black px-10 md:px-20 lg:px-20 flex flex-col justify-center ${
          isMenuOpened && !isLgScreen ? '' : 'hidden'
        }`}
      >
        <ul className='flex flex-col justify-center items-center'>
          <li className='text-3xl py-5 text-gray-500 hover:text-gray-300 cursor-pointer'>
            <ScrollLink to='about'>
              <button onClick={() => setMenuOpen(!isMenuOpened)}>About</button>
            </ScrollLink>
          </li>
          <li className='text-3xl py-5 text-gray-500 hover:text-gray-300 cursor-pointer'>
            <ScrollLink to='skills'>
              <button onClick={() => setMenuOpen(!isMenuOpened)}>Skills</button>
            </ScrollLink>
          </li>
          <li className='text-3xl py-5 text-gray-500 hover:text-gray-300 cursor-pointer'>
            <ScrollLink to='career'>
              <button onClick={() => setMenuOpen(!isMenuOpened)}>Career</button>
            </ScrollLink>
          </li>
          <li className='text-3xl py-5 text-gray-500 hover:text-gray-300 cursor-pointer'>
            <ScrollLink to='contact'>
              <button onClick={() => setMenuOpen(!isMenuOpened)}>
                Say hello
              </button>
            </ScrollLink>
          </li>
        </ul>
      </main>

      <main
        className={`mb-auto bg-gray-200 dark:bg-black ${
          isMenuOpened && !isLgScreen ? 'hidden' : ''
        }`}
      >
        <section
          className='main-section min-h-screen bg-purple-600'
          style={{
            background: 'radial-gradient(gray 1%, transparent 5%)',
            backgroundSize: '5vmin 5vmin',
            transition: 'background-size 0.3s, background-position 0.3s',
          }}
          id='landing'
        >
          <div className='text-center p-10 py-10 absolute inset-0 flex flex-col items-center justify-center'>
            <h2 className='relative py-3 font-bold text-4xl sm:text-7xl md:text-8xl lg:text-9xl group cursor-default mx-auto w-1/2 lg:w-full max-w-lg'>
              <span className='relative z-10 text-orange-500 dark:text-black group-hover:text-black dark:group-hover:text-orange-500 pointer-events-none'>
                DIEGO ARNDT
              </span>
              <span
                className='absolute inset-0 w-full skew-x-12 transition duration-300 ease-in-out origin-right bg-gray-300 dark:bg-orange-500 group-hover:bg-orange-500 dark:group-hover:bg-gray-300'
                onMouseEnter={handleHover}
                onMouseLeave={handleLeave}
              ></span>
            </h2>
            <h3 className='text-lg py-3 dark:text-gray-300 lg:text-xl tracking-widest'>
              {translation.jobTitle}
            </h3>
          </div>
        </section>

        <section
          className='min-h-screen pt-28 md:pt-48'
          style={{
            background: 'radial-gradient(gray -100%, transparent 50%)',
          }}
          id='about'
        >
          <div className='mx-auto mt-20 lg:mt-16 border-2 border-orange-500 rounded-full relative overflow-hidden h-80 w-80 lg:h-96 lg:w-96'>
            <Image
              src={myself}
              alt='profile-picture'
              layout='fill'
              objectFit='cover'
              priority={true}
              className='border-t-8-4 border-black pointer-events-none'
            />
          </div>
          <h3 className='mx-auto py-20 lg:py-16 font-bold text-orange-500 dark:text-white text-3xl lg:text-4xl max-w-sm md:max-w-lg lg:max-w-2xl xl:max-w-4xl'>
            {translation.summary}
          </h3>
          <p className='mx-auto text-justify tracking-widest text-gray-600 dark:text-white text-xl lg:text-1xl max-w-sm md:max-w-lg lg:max-w-2xl xl:max-w-4xl'>
            As a motivated front-end developer with experience in the Angular
            framework and a solid understanding of TypeScript and web
            technologies, I specialize in creating visually appealing and
            intuitive user interfaces with a focus on UI/UX design principles.
            My expertise includes collaborating with stakeholders to implement
            design best practices, optimizing layouts for usability and
            performance, and delivering top-quality user support to clients.
            Combining my artistic skills with my technical knowledge, I am
            dedicated to building dynamic and engaging web apps that provide a
            seamless user experience.
          </p>
        </section>

        <section className='min-h-screen bg-blue-600' id='skills'>
          <h2>test skills</h2>
        </section>

        <section
          className='min-h-screen pt-28 md:pt-48'
          style={{
            background: 'radial-gradient(gray -100%, transparent 50%)',
          }}
          id='career'
        >
          <div className='container mx-auto w-full h-full'>
            <div className='relative wrap overflow-hidden p-10 h-full'>
              <div
                className='border-2-2 absolute border-opacity-20 border-gray-300 h-full border'
                style={{ left: '50%' }}
              ></div>

              <div className='mb-8 flex justify-between items-center w-full right-timeline'>
                <div className='order-1 w-5/12'></div>
                <div className='z-20 flex items-center order-1 w-10 h-10'>
                  <Link href='https://www.sc.senai.br/' passHref={true}>
                    <a
                      target='_blank'
                      rel='noopener noreferrer'
                      className='hover:scale-110'
                    >
                      <img className='rounded-full' src={senai.src} />
                    </a>
                  </Link>
                </div>
                <div className='order-1 bg-blue-600 rounded-lg shadow-xl w-5/12 px-6 py-4 relative'>
                  <img
                    src={study.src}
                    className='absolute inset-0 w-full h-full object-cover opacity-10 hover:opacity-30'
                  />
                  <div className='relative w-fit'>
                    <h3 className='font-bold text-white text-xl'>
                      SENAI
                      <small className='px-1'>
                        (National Service for Industrial Training)
                      </small>
                    </h3>
                    <h6 className='mb-3'>
                      <small className='flex items-center text-white'>
                        2013 - 2014 | Blumenau, SC, Brazil
                        <span className='text-2xl px-1'>
                          &#x1F1E7;&#x1F1F7;
                        </span>
                      </small>
                    </h6>
                    <p className='text-sm leading-snug tracking-wide text-white'>
                      Vocational Program, Software Systems Development
                    </p>
                  </div>
                </div>
              </div>

              <div className='mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline'>
                <div className='order-1 w-5/12'></div>
                <div className='z-20 flex items-center order-1 w-10 h-10'>
                  <Link href='https://www.t-systems.com/' passHref={true}>
                    <a
                      target='_blank'
                      rel='noopener noreferrer'
                      className='hover:scale-110'
                    >
                      <img className='rounded-full' src={telekom.src} />
                    </a>
                  </Link>
                </div>
                <div className='order-1 bg-pink-700 rounded-lg shadow-xl w-5/12 px-6 py-4 relative'>
                  <img
                    src={work.src}
                    className='absolute inset-0 w-full h-full object-cover opacity-10 hover:opacity-30'
                  />
                  <div className='relative w-fit'>
                    <h3 className='font-bold text-white text-xl'>
                      T-Systems
                      <small className='px-1'>
                        (Information Technology Company)
                      </small>
                    </h3>
                    <h6 className='mb-3'>
                      <small className='flex items-center text-white'>
                        2014 - 2020 | Blumenau, SC, Brazil
                        <span className='text-2xl px-1'>
                          &#x1F1E7;&#x1F1F7;
                        </span>
                      </small>
                    </h6>
                    <p className='text-sm font-medium leading-snug tracking-wide text-white'>
                      From Internship to Support Analyst
                    </p>
                  </div>
                </div>
              </div>

              <div className='mb-8 flex justify-between items-center w-full right-timeline'>
                <div className='order-1 w-5/12'></div>
                <div className='z-20 flex items-center order-1 w-10 h-10'>
                  <Link href='https://www.furb.br/' passHref={true}>
                    <a
                      target='_blank'
                      rel='noopener noreferrer'
                      className='hover:scale-110'
                    >
                      <img className='rounded-full' src={furb.src} />
                    </a>
                  </Link>
                </div>
                <div className='order-1 bg-blue-900 rounded-lg shadow-xl w-5/12 px-6 py-4 relative'>
                  <img
                    src={study.src}
                    className='absolute inset-0 w-full h-full object-cover opacity-10 hover:opacity-30'
                  />
                  <div className='relative w-fit'>
                    <h3 className='font-bold text-white text-xl'>
                      FURB
                      <small className='px-1'>
                        (Regional University of Blumenau)
                      </small>
                    </h3>
                    <h6 className='mb-3'>
                      <small className='flex items-center text-white'>
                        2015 - 2020 | Blumenau, SC, Brazil
                        <span className='text-2xl px-1'>
                          &#x1F1E7;&#x1F1F7;
                        </span>
                      </small>
                    </h6>
                    <p className='text-sm leading-snug tracking-wide text-white'>
                      Bachelor's degree, Information Systems
                    </p>
                  </div>
                </div>
              </div>

              <div className='mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline'>
                <div className='order-1 w-5/12'></div>
                <div className='z-20 flex items-center order-1 w-10 h-10'>
                  <Link href='https://www.vail.com/' passHref={true}>
                    <a
                      target='_blank'
                      rel='noopener noreferrer'
                      className='hover:scale-110'
                    >
                      <img className='rounded-full' src={vail.src} />
                    </a>
                  </Link>
                </div>
                <div className='order-1 bg-gray-800 rounded-lg shadow-xl w-5/12 px-6 py-4 relative'>
                  <img
                    src={wxp.src}
                    style={{ transform: 'scaleX(-1)' }}
                    className='absolute inset-0 w-full h-full object-cover opacity-10 hover:opacity-30'
                  />
                  <div className='relative w-fit'>
                    <h3 className='font-bold text-white text-xl'>
                      Vail Resorts Inc.
                      <small className='px-1'>(Mountain Resorts)</small>
                    </h3>
                    <h6 className='mb-3'>
                      <small className='flex items-center text-white'>
                        2017 - 2018 | South Lake Tahoe, CA, United States
                        <span className='text-2xl px-1'>
                          &#x1F1FA;&#x1F1F8;
                        </span>
                      </small>
                    </h6>
                    <p className='text-sm font-medium leading-snug tracking-wide text-white'>
                      Seasonal, General services
                    </p>
                  </div>
                </div>
              </div>

              <div className='mb-8 flex justify-between items-center w-full right-timeline'>
                <div className='order-1 w-5/12'></div>
                <div className='z-20 flex items-center order-1 w-10 h-10'>
                  <Link href='https://www.veralogica.com/' passHref={true}>
                    <a
                      target='_blank'
                      rel='noopener noreferrer'
                      className='hover:scale-110'
                    >
                      <img className='rounded-full' src={veralogica.src} />
                    </a>
                  </Link>
                </div>
                <div className='order-1 bg-green-600 rounded-lg shadow-xl w-5/12 px-6 py-4 relative'>
                  <img
                    src={work.src}
                    className='absolute inset-0 w-full h-full object-cover opacity-10 hover:opacity-30'
                  />
                  <div className='relative w-fit'>
                    <h3 className='font-bold text-white text-xl'>
                      Veralogica GmbH
                      <small className='px-1'>
                        (Digital Solutions Startup)
                      </small>
                    </h3>
                    <h6 className='mb-3'>
                      <small className='flex items-center text-white'>
                        2020 - Current | Frankfurt, HE, Germany
                        <span className='text-2xl px-1'>
                          &#x1F1E9;&#x1F1EA;
                        </span>
                      </small>
                    </h6>
                    <p className='text-sm leading-snug tracking-wide text-white'>
                      Front-End Web Developer
                    </p>
                  </div>
                </div>
              </div>

              <div className='mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline'>
                <div className='order-1 w-5/12'></div>
                <div className='z-20 flex items-center order-1 w-10 h-10'>
                  <Link href='https://humber.ca/' passHref={true}>
                    <a
                      target='_blank'
                      rel='noopener noreferrer'
                      className='hover:scale-110'
                    >
                      <img
                        className='rounded-full cursor-pointer'
                        src={humber.src}
                      />
                    </a>
                  </Link>
                </div>
                <div className='order-1 bg-yellow-600 rounded-lg shadow-xl w-5/12 px-6 py-4 relative'>
                  <img
                    src={study.src}
                    className='absolute inset-0 w-full h-full object-cover opacity-10 hover:opacity-30'
                  />
                  <div className='relative w-fit'>
                    <h3 className='font-bold text-white text-xl'>
                      Humber College
                      <small className='px-1'>
                        (Institute of Technology & Advanced Learning)
                      </small>
                    </h3>
                    <h6 className='mb-3'>
                      <small className='flex items-center text-white'>
                        2022 - Current | Toronto, ON, Canada
                        <span className='text-2xl px-1'>
                          &#x1F1E8;&#x1F1E6;
                        </span>
                      </small>
                    </h6>
                    <p className='text-sm font-medium leading-snug tracking-wide text-white'>
                      Associate's degree, Web Design and Development
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section
          className='min-h-screen flex justify-center items-center'
          style={{
            background: 'radial-gradient(gray -100%, transparent 50%)',
          }}
          id='contact'
        >
          <form className='w-full max-w-2xl px-10'>
            <h3 className='mx-auto flex justify-center font-bold text-orange-500 dark:text-white text-3xl lg:text-4xl max-w-lg lg:max-w-2xl xl:max-w-4xl'>
              Thanks for taking the time to reach out.
            </h3>
            <div className='flex justify-center items-center pt-4 pb-20 lg:pb-16 mx-auto'>
              <h3 className='font-bold text-orange-500 dark:text-white text-md max-w-lg lg:max-w-2xl xl:max-w-4xl'>
                Please feel free to contact me via email at any time.
              </h3>
              <span className='text-white px-1'>
                <BsFillEnvelopeFill />
              </span>
              <span className='flex items-center text-gray-400 hover:text-orange-600'>
                <span>diegoarndt@outlook.com</span>
              </span>
            </div>
            <div className='flex flex-wrap -mx-3 mb-6'>
              <div className='w-full px-3'>
                <label
                  className='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
                  htmlFor='grid-name'
                >
                  Name
                </label>
                <input
                  className='appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white'
                  id='grid-name'
                  type='text'
                  placeholder='Your Name'
                  autoComplete='off'
                ></input>
              </div>
            </div>
            <div className='flex flex-wrap -mx-3 mb-6'>
              <div className='w-full px-3'>
                <label
                  className='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
                  htmlFor='grid-email'
                >
                  Email
                </label>
                <input
                  className='appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white'
                  id='grid-email'
                  type='email'
                  placeholder='Your Email Address'
                  autoComplete='off'
                ></input>
              </div>
            </div>
            <div className='flex flex-wrap -mx-3 mb-6'>
              <div className='w-full px-3'>
                <label
                  className='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
                  htmlFor='grid-message'
                >
                  Message
                </label>
                <textarea
                  className='appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white'
                  id='grid-message'
                  rows='8'
                  placeholder='Your Message'
                ></textarea>
              </div>
            </div>
            <div className='flex items-center justify-end'>
              <button
                className='shadow bg-orange-600 hover:bg-orange-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded w-32'
                type='button'
              >
                Send
              </button>
            </div>
          </form>
        </section>
      </main>

      <footer className='border-t-2 border-orange-600 text-center py-10 text-gray-600 bg-gray-200 dark:bg-black dark:text-gray-400'>
        <div className='mx-auto max-w-3xl'>
          <blockquote className='text-lg text-gray-600 italic my-1 mx-6 pl-4 px-4 border-l-4 border-orange-500'>
            &quot;{translation.quote}&quot; &ndash; Cory House
          </blockquote>
        </div>
        <div className='text-5xl py-5 flex justify-center gap-16 text-gray-600 dark:text-gray-400'>
          <Link href='https://gitlab.com/diegoarndt' passHref={true}>
            <a
              target='_blank'
              rel='noopener noreferrer'
              className='hover:scale-110 hover:text-orange-600'
            >
              <AiFillGitlab />
            </a>
          </Link>
          <Link href='https://github.com/diegoarndt' passHref={true}>
            <a
              target='_blank'
              rel='noopener noreferrer'
              className='hover:scale-110 hover:text-purple-600'
            >
              <AiFillGithub />
            </a>
          </Link>
          <Link href='https://www.linkedin.com/in/diegoarndt' passHref={true}>
            <a
              target='_blank'
              rel='noopener noreferrer'
              className='hover:scale-110 hover:text-blue-600'
            >
              <AiFillLinkedin />
            </a>
          </Link>
        </div>
        <p>
          {translation.handcrafted} ©&nbsp;
          <span>
            <YearInWords language={props.locale} />
          </span>
        </p>
      </footer>
    </div>
  );
}
